---
sudo: required
language: ruby
cache: bundler

# necessary for docker to work
dist: trusty
services:
  - docker

bundler_args: --without integration guard tools

before_install:
  # we need bundler to take ruby version into consideration
  # https://github.com/bundler/bundler/issues/4046
  - gem install bundler -v '~> 1.11.2'
  - gem --version

matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
      bundler_args: --without guard tools
      script: bundle exec rake test:integration
  allow_failures:
    - rvm: ruby-head
