sudo: required
branches:
  only:
    - master
language: ruby
cache: bundler
dist: trusty
services:
  - docker
bundler_args: "--without integration guard tools"
before_install:
  - gem update --system
  - gem --version
  - rvm @global do gem install bundler
  - bundle --version
matrix:
  include:
  - rvm: 2.3.6
  - rvm: 2.4.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE="test:integration" OS='default profile contains_inspec'
  - rvm: 2.4.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE="test:integration" OS='backwards'
  - rvm: 2.4.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE="test:integration" OS='duplicates'
  - rvm: 2.4.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE="test:integration" OS='supermarket'
  - rvm: 2.4.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE="test:integration" OS='attributes-inline attributes-file'
  - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
